### ISSUE TITLE
builder_runner_test fails when executing on machines with a running docker daemon

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/dockerapplifecycle#6]
Running units on a machine that has docker for mac installed results in consistent failures:

```
• Failure [0.018 seconds]
Builder runner when the daemon won't start [It] times out 
/Users/sykesm/workspace/diego-release/src/github.com/cloudfoundry-incubator/docker_app_lifecycle/builder/builder_runner_test.go:59

  Expected
      <string>: Exit trace for group:
      builder exited with error: failed to fetch metadata from [ubuntu] with tag [latest] and insecure registries [] due to Get http:///v2/: http: no Host in request URL
      fake_docker_daemon exited with error: interrupt
      
  to contain substring
      <string>: Timed out waiting for docker daemon to start

  /Users/sykesm/workspace/diego-release/src/github.com/cloudfoundry-incubator/docker_app_lifecycle/builder/builder_runner_test.go:58
```

**Comment by ematpl** [comment]
Thanks, @sykesm. I'll prioritize the corresponding story to get this fixed.

Best,
Eric

**Comment by cwlbraa** [comment]
We need to get an invite to the docker for mac private beta in order to fix this. we submitted a request to docker via the cf-diego+docker account.

**Comment by ematpl** [comment]
Oh, that's where that email to the team list came from. If this is related to the image-caching mode of the builder's operation, it's also on the table to rip all that out.

**Comment by sykesm** [comment]
@cwlbraa if you want, you can catch me on SH and I can demonstrate and let you poke around. As soon as I stop the docker system, everything is fine.

**Comment by ematpl** [comment]
Hey, @sykesm, 

We expect that work done in https://www.pivotaltracker.com/n/projects/1003146/stories/122699661 has fixed this issue as well. Could you confirm whether that's the case?

Thanks,
Eric

**Comment by ematpl** [comment]
Closing, as it seems that this issue is fixed now.
