### ISSUE TITLE
detect and convey different builder failure modes through exit codes

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/dockerapplifecycle#8]
If we fail to build a docker image because we've provided an invalid or nonexistent image name, the app lifecycle currently does not convey any failure info to the cloud controller, so the cloud controller cannot give helpful error messages to the user.

If we could replicate the approach used by the buildpack app lifecycle, we could also have better docker error messages.

see https://github.com/cloudfoundry/cloud_controller_ng/issues/885 for original issue.

**Comment by emalm** [comment]
Thanks, @cwlbraa, do you have particular known failure modes that you think would be most important to cover? I'm also interested to hear from @zrob or @crawsible on this, since CC would also have to change to recognize those particular codes.

**Comment by cwlbraa** [comment]
I think the underlying containers/image client bubbles up status codes, so I guess 400, 401, 403, and especially 404 are the most relevant ones. Maybe timeout as well? Not sure, really. 

FWIW I'm sure this isn't super high priority, I was just community-pair-ferrying along that ccng issue to the repo where the changes would have to start.

**Comment by emalm** [comment]
Ha, fair enough on the issue transfer. I could see failure to connect to the remote registry (on timeout or connection refused) and failure to be authorized to pull the image being a couple of important ones, so maybe that's sufficient to start.

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, and given current priorities and resource availability we're not going to be in a position to work on this so I'm going to go ahead and close it.
