### ISSUE TITLE
Authentication not working when redirected

### ISSUE THREAD

**Issue by sonman** [cloudfoundry/dockerapplifecycle#9]
Hi,

because of a migration we have a redirect from private-registry.internal to mydocker-registry.internal.

**Problem:**
cf push "imagapp" --docker-image "private-registry.internal/imageapp:latest"--no-manifest -i "1"
`Staging...
   Staging process started ...
   Failed getting docker image manifest by tag: unauthorized  Going to retry attempt: 1
   Failed getting docker image manifest by tag: unauthorized  Going to retry attempt: 2
   Failed getting docker image manifest by tag: unauthorized  Going to retry attempt: 3
   Failed getting docker image manifest by tag: unauthorized`

But local docker pull is working:
docker pull private-registry.internal/imageapp:latest

**Investigation:**
**Test1:**
cf push "imagapp" --docker-image "private-registry.internal/imageapp:latest"--no-manifest -i "1"
Nginx log:

<SOURCE_IP> - - [TIMESTAMP] "GET /v2/ HTTP/1.1" 308 171 "-" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /v2/ HTTP/1.1" 401 87 "https://private-registry.internal/v2/" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /api/docker/docker/v2/token?scope=repository%3Aimageapp%3Apull&service=mydocker-registry.internal%3A443 HTTP/1.1" 200 114 "-" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /v2/webapp/manifests/latest HTTP/1.1" 308 171 "-" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /v2/webapp/manifests/latest HTTP/1.1" **401** 87 "https://private-registry.internal/v2/webapp/manifests/latest" "Go-http-cli

I assume that the token is stored for the redirection target (mydocker-registry.internal) but not for the docker image tag (private-registry.internal).

**Test2:**
cf push "imagapp" --docker-image "mydocker-registry.internal/imageapp:latest"--no-manifest -i "1"
<SOURCE_IP> - - [TIMESTAMP] "GET /v2/ HTTP/1.1" 401 87 "https://mydocker-registry.internal/v2/" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /api/docker/docker/v2/token?scope=repository%3Aimageapp%3Apull&service=mydocker-registry.internal%3A443 HTTP/1.1" 200 114 "-" "Go-http-client/1.1" "-"
<SOURCE_IP> - - [TIMESTAMP] "GET /v2/webapp/manifests/latest HTTP/1.1" **200** 2821 "https://mydocker-registry.internal/v2/webapp/manifests/latest" "Go-http-cli

Test2 is working since no redirection is made.

**Expected result:**
cf push "imagapp" --docker-image "mydocker-registry.internal/imageapp:latest"--no-manifest -i "1" works.

(Hint: When I disable redirection in the reverse proxy. It works.)

**Comment by aminjam** [comment]
@sonman We've been unable to reproduce the issue using the [azure container registry](https://azure.microsoft.com/en-us/services/container-registry/). Can you please provide us the following items so we can reproduce this issue:

- `nginx.conf` that mimics the proxy behavior explained above
- [`dockerapplifecycle-builder`](https://github.com/cloudfoundry/dockerapplifecycle/blob/4d909ee2ae984892af9c42d5c055012af1604cb4/builder/main.go) command line with arguments (no passwords) that causes the above error.

**Comment by heyjcollins** [comment]
Hello @sonman - I'm going to go ahead and close this issue since it's been inactive for over 30 days. Feel free to comment, provide the items requested by @aminjam ,  and reopen if you'd like to continue.
